clean_log: true

dataset: 
    original: data
    curated: feature_ds

weights:
    acousticness: 0.115
    energy: 0.105
    danceability: 0.1
    instrumentalness: 0.095
    tempo: 0.09
    mode: 0.085
    loudness: 0.085
    speechiness: 0.08
    liveness: 0.08
    valence: 0.08
    year: 0.05
    popularity: 0.035

distance_algorithm:
    distmax: Distance.get_cosine_similarity
    distmin: Distance.get_euclidean_distance
    eval_func: CentralTendencies.get_mean
    minimmum_songs: 3
    query_songs_limit: 6
    query_artists_limit: 3
    results_count: 10
    threshold_year: 1965