clean_log: true

dataset: data.csv

weights:
    acousticness: 0.135
    danceability: 0.115
    energy: 0.115
    mode: 0.105
    tempo: 0.095
    instrumentalness: 0.095
    speechiness: 0.09
    loudness: 0.085
    liveness: 0.08
    valence: 0.075
    popularity: 0.01

distance_algorithm:
    algorithm: Distance.get_euclidean_distance
    eval_func: min
    results_count: 50
    song_cutoff_year: 1965