clean_log: true

dataset: 
    original: data
    curated: feature_ds

weights:
    acousticness: 0.130
    danceability: 0.105
    energy: 0.105
    tempo: 0.09
    instrumentalness: 0.085
    mode: 0.085
    loudness: 0.08
    speechiness: 0.08
    liveness: 0.08
    valence: 0.075
    year: 0.06
    popularity: 0.025

distance_algorithm:
    distmax: Distance.get_cosine_similarity
    distmin: Distance.get_euclidean_distance
    results_count: 50
    threshold_year: 1965