clean_log: true

dataset: data_test.csv

weights:
    acousticness: 0.135
    danceability: 0.12
    energy: 0.12
    tempo: 0.095
    instrumentalness: 0.095
    mode: 0.09
    speechiness: 0.09
    loudness: 0.085
    liveness: 0.08
    valence: 0.075
    popularity: 0.01

distance_algorithm:
    algorithm: Distance.get_euclidean_distance
    eval_func: min
    results_count: 50
    threshold_year: 1965