version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - "cluster.name=elasticsearch"
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=1
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - elk
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  server-backend:
    build: .
    restart: always
    container_name: server-backend
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
    depends_on:
      - elasticsearch
    volumes:
      - .:/server
    networks:
      - elk

volumes:
  elasticsearch-data:
    driver: local

networks:
  elk:
    driver: bridge